config/routes.rb
Refinery::Core::Engine.routes.draw do
  namespace :news, :path => '/teachings/dhammapada-reflections' do
    root :to => "items#index"
    get 'archive/:year(/:month)', :to => 'items#archive', :as => 'items_archive', :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ }
    resources :items, :only => [:show, :index], :path => ''
  end

  namespace :news, :path => '' do
    namespace :admin, :path => Refinery::Core.backend_route do
      scope :path => 'reflections' do
        root :to => "items#index"
        resources :items, :except => :show
      end
    end
  end
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  translates :title, :body

  attr_accessor :locale # to hold temporarily

  alias_attribute :content, :body
  validates :title, :content, :publish_date, :presence => true

  has_friendly_id :title, :use_slug => true

  acts_as_indexed :fields => [:title, :body, :source]

  default_scope :order => "news_items.publish_date DESC, news_items.created_at DESC"

  # If you're using a named scope that includes a changing variable you need to wrap it in a lambda
  # This avoids the query being cached thus becoming unaffected by changes (i.e. Time.now is constant)
  scope :not_expired, lambda {
    news_items = Arel::Table.new(NewsItem.table_name)
    where(news_items[:expiration_date].eq(nil).or(news_items[:expiration_date].gt(Time.now)))
  }
  scope :published, lambda {
    not_expired.where("publish_date < ?", Time.now)
  }
  scope :latest, lambda { |*l_params|
    published.limit( l_params.first || 10)
  }

  # rejects any page that has not been translated to the current locale.
  scope :translated, lambda {
    pages = Arel::Table.new(NewsItem.table_name)
    translations = Arel::Table.new(NewsItem.translations_table_name)

    includes(:translations).where(
      translations[:locale].eq(Globalize.locale)).where(pages[:id].eq(translations[:news_item_id]))
  }

  def not_published? # has the published date not yet arrived?
    publish_date > Time.now
  end

  # for will_paginate
  class << self
    attr_accessor :per_page
    def per_page
      @per_page ||= 20
    end
  end

end

app/controllers/admin/news_items_controller.rb
class Admin::NewsItemsController < Admin::BaseController
  before_filter :show_preview, :only => [:new, :edit, :create]
  before_filter :has_image, :only => [:new, :edit, :create]

  crudify :news_item, :order => "publish_date DESC"

  protected
  def show_preview
    @show_preview ||= RefinerySetting.find_or_set(:refinery_news_show_preview, true)
  end
  
  def has_image
    @has_image ||= RefinerySetting.find_or_set(:refinery_news_has_image, true)
  end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_filter :find_page
  before_filter :find_published_news_items, :only => [:index]
  before_filter :find_news_item, :find_latest_news_items, :only => [:show]

  def index
    # render 'index'
  end

  def show
    # render 'show'
  end

protected

  def find_latest_news_items
    @news_items = NewsItem.latest.translated
  end

  def find_published_news_items
    @news_items = NewsItem.published.translated.paginate(
      :page => params[:page],
      :per_page => NewsItem.per_page
    )
  end

  def find_news_item
    @news_item = NewsItem.published.translated.find(params[:id])
  end

  def find_page
    @page = Page.find_by_link_url("/news")
  end

end

app/views/news_items/index.html.erb
<% content_for :body_content_left do %>
  <%=raw @page.content_for(Page.default_parts.first.to_sym) if @news_items.offset == 0 %>

  <% if @news_items.any? %>
    <% @news_items.each do |item| %>
      <article class="news_item_truncated">
        <h2><%= link_to item.title, news_item_url(item) %></h2>
        <p>
          <small><%= t('.published') %> <%= l(item.publish_date, :format => :long) %></small>
        </p>
        <% if item.source.present? %>
          <p>
            <small><%= t('.source') %> <%= item.source %></small>
          </p>
        <% end %>
        <%= truncate  item.body, :length => 200,
                      :omission => " ... #{link_to t('.read_more'), news_item_url(item)}",
                      :preserve_html_tags => true %>
      </article>
    <% end %>

    <%= will_paginate(@news_items) %>
  <% else %>
    <p><em><%= t('.no_items_yet') %></em></p>
  <% end %>
<% end -%>

<%= render :partial => "/shared/content_page" %>

app/views/news_items/show.html.erb
<% content_for :body_content_title, @news_item.title %>
<% content_for :body_content_left do %>
  <article class="news_item">
    <p>
      <small><%= t('.published') %> <%= l(@news_item.publish_date, :format => :long) %></small>
    </p>
    <% if @news_item.source.present? %>
      <p>
        <small><%= t('.source') %> <%= @news_item.source %></small>
      </p>
    <% end %>
    <%= @news_item.body.html_safe %>
    <p>
      <%= link_to t('.back_to_index'), news_items_url %>
    </p>
  </article>
<% end %>
<% content_for :body_content_right, render(:partial => 'recent_posts') %>

<%= render :partial => "/shared/content_page" %>