config/routes.rb
Refinery::Core::Engine.routes.draw do
  namespace :news, :path => '/teachings/dhammapada-reflections' do
    root :to => "items#index"
    get 'archive/:year(/:month)', :to => 'items#archive', :as => 'items_archive', :constraints => { :year => /\d{4}/, :month => /\d{1,2}/ }
    resources :items, :only => [:show, :index], :path => ''
  end

  namespace :news, :path => '' do
    namespace :admin, :path => Refinery::Core.backend_route do
      scope :path => 'reflections' do
        root :to => "items#index"
        resources :items, :except => :show
      end
    end
  end
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  translates :title, :body

  attr_accessor :locale # to hold temporarily

  alias_attribute :content, :body
  validates :title, :content, :publish_date, :presence => true

  has_friendly_id :title, :use_slug => true

  acts_as_indexed :fields => [:title, :body, :source]

  default_scope :order => "news_items.publish_date DESC, news_items.created_at DESC"

  # If you're using a named scope that includes a changing variable you need to wrap it in a lambda
  # This avoids the query being cached thus becoming unaffected by changes (i.e. Time.now is constant)
  scope :not_expired, lambda {
    news_items = Arel::Table.new(NewsItem.table_name)
    where(news_items[:expiration_date].eq(nil).or(news_items[:expiration_date].gt(Time.now)))
  }
  scope :published, lambda {
    not_expired.where("publish_date < ?", Time.now)
  }
  scope :latest, lambda { |*l_params|
    published.limit( l_params.first || 10)
  }

  # rejects any page that has not been translated to the current locale.
  scope :translated, lambda {
    pages = Arel::Table.new(NewsItem.table_name)
    translations = Arel::Table.new(NewsItem.translations_table_name)

    includes(:translations).where(
      translations[:locale].eq(Globalize.locale)).where(pages[:id].eq(translations[:news_item_id]))
  }

  def not_published? # has the published date not yet arrived?
    publish_date > Time.now
  end

  # for will_paginate
  class << self
    attr_accessor :per_page
    def per_page
      @per_page ||= 20
    end
  end

end

app/controllers/admin/news_items_controller.rb
class Admin::NewsItemsController < Admin::BaseController
  before_filter :show_preview, :only => [:new, :edit, :create]
  before_filter :has_image, :only => [:new, :edit, :create]

  crudify :news_item, :order => "publish_date DESC"

  protected
  def show_preview
    @show_preview ||= RefinerySetting.find_or_set(:refinery_news_show_preview, true)
  end
  
  def has_image
    @has_image ||= RefinerySetting.find_or_set(:refinery_news_has_image, true)
  end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_filter :find_page
  before_filter :find_published_news_items, :only => [:index]
  before_filter :find_news_item, :find_latest_news_items, :only => [:show]

  def index
    # render 'index'
  end

  def show
    # render 'show'
  end

protected

  def find_latest_news_items
    @news_items = NewsItem.latest.translated
  end

  def find_published_news_items
    @news_items = NewsItem.published.translated.paginate(
      :page => params[:page],
      :per_page => NewsItem.per_page
    )
  end

  def find_news_item
    @news_item = NewsItem.published.translated.find(params[:id])
  end

  def find_page
    @page = Page.find_by_link_url("/news")
  end

end

app/views/admin/news_items/_form.html.erb
<%= form_for [:admin, @news_item] do |f| %>
  <%= render :partial => "/shared/admin/error_messages",
             :locals => {
               :object => @news_item,
               :include_object_name => true
             } %>

  <%= render :partial => "locale_picker",
             :locals => {
               :current_locale => Thread.current[:globalize_locale]
             } if defined?(::Refinery::I18n) %>

  <div class='field'>
    <%= f.label :title %>
    <%= f.text_field :title, :class => "larger widest" %>
  </div>

  <div class='field'>
    <%= f.label :publish_date %>
    <%= f.datetime_select :publish_date %>
  </div>

  <div class='field'>
    <%= f.label :expiration_date %>
    <%= f.datetime_select :expiration_date, :start_year => Time.now.year,
                                            :include_blank => true %>
  </div>

  <div class='field'>
    <%= f.label :body %>
    <%= f.text_area :body, :rows => "20", :class => "wymeditor widest" %>
  </div>

  <div class='field'>
    <%= f.label :source %>
    <%= f.text_field :source, :class => "larger widest" %>
  </div>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => true,
               :delete_title => t('admin.news_items.news_item.delete'),
               :delete_confirmation => t('shared.admin.delete.message', :title => @news_item.title)
             } %>

<% end %>

app/views/admin/news_items/_locale_picker.html.erb
<input type='hidden' name='switch_locale' id='switch_locale' value='<%= local_assigns[:current_locale] %>' />
<% if (locales ||= ::Refinery::I18n.frontend_locales).present? and locales.many? %>
  <ul id='switch_locale_picker' class='clearfix'>
    <% locales.each do |locale| %>
      <li<%= " class='selected'" if locale.to_s == local_assigns[:current_locale].to_s %>>
        <%= link_to refinery_icon_tag("flags/#{locale}.png", :size => '48x33'),
                    url_for(:switch_locale => locale) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/admin/news_items/_news_item.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title'>
    <%= news_item.title %>
    <span class="preview">
      <%= t('.published') %> <%= l(news_item.publish_date, :format => :short) %>
    </span>
    <% if defined?(::Refinery::I18n) and ::Refinery::I18n.frontend_locales.many? and
          (locales = news_item.translations.collect{|t| t.locale}).present? %>
      <span class='preview'>
        <% locales.each do |locale| %>
          <%= refinery_icon_tag "flags/#{locale}.png", :size => '16x11' %>
        <% end %>
      </span>
    <% end %>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('application_go.png'), news_item_url(news_item),
                :title => t('.view_live_html'),
                :target => "_blank" %>
    <%= link_to refinery_icon_tag('application_edit.png'), edit_admin_news_item_path(news_item),
                :title => t('.edit') %>
    <%= link_to refinery_icon_tag('delete.png'), admin_news_item_path(news_item),
                :class => "cancel confirm-delete",
                :title => t('.delete'),
                :method => :delete,
                :confirm => t('shared.admin.delete.message', :title => news_item.title) %>
  </span>
</li>